version: "3"

services:
  flask-app:
    build: .
    ports:
      - "5001:5000" # 호스트의 5001 포트를 컨테이너의 5000 포트(Flask의 기본 포트)에 매핑
    volumes:
      - .:/app # 호스트의 현재 디렉토리를 컨테이너의 /app 디렉토리에 매핑
        # 이를 통해 코드 변경 시 컨테이너를 재시작하지 않고도 변경사항을 반영 가능
    env_file:
      - ../../.env
